### ISSUE TITLE
连接失败之后，再次请求的时候TSocket变成nil

### ISSUE THREAD

**Issue by szmcdull** [gityf/ngx_lua_thrift#2]
function main()
	
		require 'TBinaryProtocol'
		ngx.say(package.loaded['TSocket']) -- 1
		require 'TSocket'
		ngx.say(inspect(TSocket)) -- 2
		require 'Trade_TradeRpc'

		local socket = TSocket:new { host = '192.168.11.164', port = 9090 }
		local protocol = TBinaryProtocol:new { trans = socket }
		local client = TradeRpcClient:new{
			protocol = protocol
		}

		socket:open()

		req = GetSymbolsReqThrift:new{
			Head = TradeHeadThrift:new {
				AccID = 123,
				AccType = TAccType['TAcc_Type_Customer'],
				RetCode = TRetCode['RTC_UNKNOWN_ERROR']
			}
		}

		local rsp = client:GetSymbols(req)
		ngx.say(inspect(rsp))
	
	end

	local success, err = pcall(main)
	if not success then
		ngx.say(inspect(err)) -- 3
		ngx.say(inspect(TSocket)) -- 4
	end

以上脚本，执行两次，第一次连接失败，执行第二次的时候，TSocket变成了nil。
其中标记为1234的4处日志，两次执行的结果分别如下：
第一次：
package.loaded['TSocket'] 为 nil
TSocket为对象
err为"/usr/local/openresty/lualib/libthrift/Thrift.lua:37: TTransportException: Could not connect to 192.168.11.164:9090 (timeout)"
TSocket仍然为合法对象
第二次：
package.loaded['TSocket']为true，表示模块已经加载过
TSocket为nil！
err为"/mnt/hgfs/code/lua/LuaThrift/main.lua:24: attempt to index global 'TSocket' (a nil value)"
最后TSocket为nil

很奇怪，为什么执行第二次的时候，TSocket就变成nil了，但是package.loaded['TSocket']又是true，百思不得其解，请问您知道是什么原因吗

**Comment by szmcdull** [comment]
https://github.com/openresty/lua-nginx-module#lua-variable-scope

**Comment by szmcdull** [comment]
看了代码，TSocket等“类”实际上是global variable，在nginx-lua里面，module是跨请求的，只会加载一次，但global是不能跨请求的，因此有这样的问题！

**Comment by mygityf** [comment]
一般ngx_lua都使用local方式使用，一次加载，多次使用。
