### ISSUE TITLE
ngx.socket.tcp长连接复用很低

### ISSUE THREAD

**Issue by sdcuike** [gityf/ngx_lua_thrift#4]
发现，压测过程中，复用率很低，不知道什么情况，抓包发现，网络连接很多用一次主动关闭了

**Comment by mygityf** [comment]
function _M.demoFunc()
    local socket = TSocket:new{
        host='127.0.0.1',
        port=8090,
        connections=30
    }
end

可以尝试连接时，增加connections参数，启用长连接。
另外，可以把socket变量设置为 _M模块的成员，调用之前做一下初始化，后期使用时，使用_M.socket 代替。
例如api.lua文件初始化部分
....

function _M.init()
   _M.socket = TSocket:new{
        host='127.0.0.1',
        port=8090,
        connections=30
    }
end
....
return _M
